#ifndef DATABASESOLUTION_GLOBAL_H
#define DATABASESOLUTION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATABASESOLUTION_LIBRARY)
#define DATABASESOLUTION_EXPORT Q_DECL_EXPORT
#else
#define DATABASESOLUTION_EXPORT Q_DECL_IMPORT
#endif

#endif // DATABASESOLUTION_GLOBAL_H
